name: Publish VS Code Extension

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # This is required for creating releases

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: npm install
        
      - name: Package Extension with consistent name
        run: |
          npm run package
          # Find and rename the VSIX file
          VERSION=$(node -p "require('./package.json').version")
          find . -name "claude-restarter-*.vsix" -exec cp {} claude-restarter.vsix \;
          ls -la *.vsix
        
      - name: Publish to VS Code Marketplace
        run: npx @vscode/vsce publish -p ${{ secrets.VSCE_PAT }}
        
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: "claude-restarter.vsix"
          generate_release_notes: true 